Homework for Lesson_5
liza-pysarenko/aqa_course pull request #3
Opened 2024-03-10 11:44 UTC by liza-pysarenko

2024-03-10 15:49 UTC, dyakov22 requested changes

2024-03-10 15:49 UTC, dyakov22 commented on homework_lesson_5.py
> +        raise ValueError("The square root of a negative number cannot be calculated.")
тут повинна бути помилка створена тобою

2024-03-10 15:49 UTC, dyakov22 commented on homework_lesson_5.py
> +        raise ValueError("The square root of a negative number cannot be calculated.")
(Тут потрібно додати перевірку на відʼємне число та якщо воно дійсно таке, то спонукати помилку за допомогою ключового слова raise, та створіть свою помилку котра будете спонукати)

2024-03-10 15:49 UTC, dyakov22 commented on homework_lesson_5.py
> +            if num1 == 'stop':
ти у попередньому рядку нам1 перетворюєш на флоат, а далі намагається порівняти флоат зі стрінгою 
тому і отримуєш помилку ValueError котру обробляєш

2024-03-10 15:49 UTC, dyakov22 commented on homework_lesson_5.py
> +        raise ValueError("The square root of a negative number cannot be calculated.")  # не можу зрозуміти, що не так, бо коли ввожу мінусове число, то отримую одразу дві помилки "Error: 'The square
ти ж сама викликаєшь помилку ВєльюЕррор 
та відловлюєшь її на 27-28 строках
тому в тебе і є помилка як Error: 'The square root of a negative.....
в таких випадках дуже допомагає дебаг, для цього його і проходили на минулому занятті)))

2024-03-10 15:49 UTC, dyakov22 commented on homework_lesson_5.py
> +            if num1 == 'stop':
тобі потрібно спочатку перевірити слово стоп а потім вже перетворити на число)

2024-03-10 19:34 UTC, liza-pysarenko commented
дуже дякую, переробила)

2024-03-14 08:39 UTC, dyakov22 approved these changes
додавай будь ласка у лмс повідомлення що ти зробила зміни) 
то я випадково побачив новий реквест на ревью)

2024-03-14 08:40 UTC, dyakov22 commented
все чудово)

2024-03-14 09:54 UTC, merged